"""
telegram_autobot.py  —  Railway-ready Telegram Userbot
────────────────────────────────────────────────────────
Environment variables required on Railway:
  API_ID          → integer from my.telegram.org/apps
  API_HASH        → string  from my.telegram.org/apps
  SESSION_STRING  → generated by generate_session.py (run locally first)
  AUTO_REPLY_MSG  → (optional) custom auto-reply message

Commands (send from your own Telegram account):
  /on      → enable auto-reply
  /off     → disable auto-reply
  /status  → check current state
"""

import os
import asyncio
import logging
from telethon import TelegramClient, events
from telethon.sessions import StringSession
from telethon.network import ConnectionTcpFull

# ── Logging (shows errors in Railway logs) ────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s"
)
logger = logging.getLogger(__name__)

# ─── Config from environment variables ───────────────────
API_ID         = 30779174
API_HASH       = "d5e27c8c4e30129238716a83df45b1f8"
SESSION_STRING = "1BVtsOIwBu3T9i2aL6z86Ory4gxwjNvIN4cYWZgNUP901zXoeWFjxf3hpc5Sw6cAmzjaIWB8ZE-CUx4kMQlc8aXNCf2iUrkXSocld3ODqREko6KuNxeL2mV4LjcgJlffBlYWq-fH_I0B_raQA9FvdMThiMDjyiw7kHh_UGJTHn1a4LV2822WoD2enV0W5thV0KXLZPsziJnTmdIiBMxiScBWI9kprEeDujVBttvl6knz3wLd4gbSm9BpxLEtInIJFu0uUS2ALRGQ0bGkVrHMFWw5hEkkeWuA9RhBN1CRy24ohjg7LTx5KoEWSoo5kig43t7UjHX-fTkOcX1scMRFSS8b4vZSHc94="
AUTO_REPLY_MESSAGE = os.environ.get(
    "AUTO_REPLY_MSG",
    "👋 Hey! I'm currently unavailable.\nI'll get back to you as soon as possible. 🙏"
)
# ─────────────────────────────────────────────────────────

# ConnectionTcpFull + sequential_updates fixes Railway/cloud update issues
client = TelegramClient(
    StringSession(SESSION_STRING),
    API_ID,
    API_HASH,
    connection=ConnectionTcpFull,
    sequential_updates=True,
    receive_updates=True,
)

is_active: bool = True


# ── Owner commands ────────────────────────────────────────
@client.on(events.NewMessage(outgoing=True, pattern=r"^/on$"))
async def cmd_on(event):
    global is_active
    is_active = True
    await event.edit("✅ Auto-reply **enabled**.")
    logger.info("Auto-reply ENABLED by owner.")


@client.on(events.NewMessage(outgoing=True, pattern=r"^/off$"))
async def cmd_off(event):
    global is_active
    is_active = False
    await event.edit("🔴 Auto-reply **disabled**.")
    logger.info("Auto-reply DISABLED by owner.")


@client.on(events.NewMessage(outgoing=True, pattern=r"^/status$"))
async def cmd_status(event):
    state = "✅ Active" if is_active else "🔴 Inactive"
    await event.edit(f"Auto-reply status: **{state}**")


# ── Incoming private messages ─────────────────────────────
@client.on(events.NewMessage(incoming=True, func=lambda e: e.is_private))
async def handle_incoming(event):
    try:
        logger.info(f"📩 Message received from user {event.sender_id}")

        if not is_active:
            logger.info("↩️  Skipped — auto-reply is OFF")
            return

        await event.reply(AUTO_REPLY_MESSAGE)
        logger.info(f"✅ Auto-replied → user {event.sender_id}")

    except Exception as e:
        logger.error(f"❌ Error in handle_incoming: {e}")


# ── Entry point ───────────────────────────────────────────
async def main():
    await client.connect()

    if not await client.is_user_authorized():
        logger.error("❌ Session is not authorized! Regenerate your SESSION_STRING.")
        return

    me = await client.get_me()
    logger.info(f"✅ Logged in as: {me.first_name} (@{me.username})")
    logger.info(f"   Auto-reply: {'ON' if is_active else 'OFF'}")
    logger.info("   Listening for messages...")

    await client.run_until_disconnected()


if __name__ == "__main__":
    asyncio.run(main())
